version: "{build} ~ {branch}"

os: Visual Studio 2017

branches:
  only:
    - staging
    - trying
    - master

environment:
  matrix:
    - CHANNEL: stable
      ARCH: x86_64
      ABI: msvc
      TARGET: x86_64-pc-windows-msvc

cache:
  - 'C:\Users\appveyor\.cargo'
  - target

install:
  # Install LLVM
  - mkdir C:\projects\deps
  - cd C:\projects\deps
  - appveyor DownloadFile https://github.com/wasmerio/windows-llvm-build/releases/download/v8.0.0/llvm-8.0.0-install.zip -FileName llvm-8.0.0-install.zip
  - 7z x llvm-8.0.0-install.zip
  - C:\projects\deps\llvm-8.0.0-install\bin\llvm-config.exe --version
  - set "LLVM_SYS_80_PREFIX=C:\projects\deps\llvm-8.0.0-install"
  - cd "%APPVEYOR_BUILD_FOLDER%"

  # Install Rust
  # uncomment these lines if the cache is cleared, or if we must re-install rust for some reason
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -yv --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustup default stable-%target%
  - rustup update
  - rustc -vV
  - cargo -vV

  # Install InnoSetup
  - appveyor-retry appveyor DownloadFile https://s3-us-west-1.amazonaws.com/rust-lang-ci2/rust-ci-mirror/2017-08-22-is.exe
  - 2017-08-22-is.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
  - set PATH="C:\Program Files (x86)\Inno Setup 5";%PATH%
# uncomment to RDP to appveyor
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
  - cargo build --release --verbose --features backend-llvm
  - cargo build --release --manifest-path lib/runtime-c-api/Cargo.toml

test_script:
  - cargo test --manifest-path lib/spectests/Cargo.toml --release --features clif -- --nocapture

before_deploy:
  - appveyor PushArtifact target\release\wasmer_runtime_c_api.dll
  - git submodule init
  - git submodule update
  - cargo build --release --manifest-path wapm-cli/Cargo.toml --features "telemetry update-notifications"
  - cd ./src/installer
  - iscc wasmer.iss
  - copy /y .\WasmerInstaller.exe ..\..\WasmerInstaller-%APPVEYOR_REPO_TAG_NAME%.exe
  - appveyor PushArtifact ..\..\WasmerInstaller-%APPVEYOR_REPO_TAG_NAME%.exe
  - cd ..\..\

matrix:
  fast_finish: true

deploy:
  description: 'WasmerInstaller'
  artifact: /.*\.exe/
  auth_token:
    secure: BbreGNDJy20922za7OhJG5TERzfX+dJSBQwttNTJkLvszbqMov6hhAtRb3P45hpf
  provider: GitHub
  on:
    branch: master
    appveyor_repo_tag: true
